downgrade freetype and sdl_ttf version to fix noesis01 crash bug

diff --git a/onscripter-libretro/deps/freetype/configure b/onscripter-libretro/deps/freetype/configure
--- a/onscripter-libretro/deps/freetype/configure
+++ b/onscripter-libretro/deps/freetype/configure
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (C) 2002-2023 by
+# Copyright 2002, 2003, 2004, 2005, 2006 by
 # David Turner, Robert Wilhelm, and Werner Lemberg.
 #
 # This file is part of the FreeType project, and may only be used, modified,
@@ -15,29 +15,19 @@
 
 rm -f config.mk builds/unix/unix-def.mk builds/unix/unix-cc.mk
 
-# respect GNUMAKE environment variable for backward compatibility
 if test "x$GNUMAKE" = x; then
-  if test "x$MAKE" = x; then
-    if test "x`make -v 2>/dev/null | grep -E 'GNU|makepp'`" = x; then
-      MAKE=gmake
-    else
-      MAKE=make
-    fi
-  fi
-else
-  MAKE=$GNUMAKE
+  GNUMAKE=make
 fi
 
-if test "x`$MAKE -v 2>/dev/null | grep -E 'GNU|makepp'`" = x; then
-  echo "GNU make (>= 3.81) or makepp (>= 2.0) is required to build FreeType2." >&2
-  echo "Please try" >&2
-  echo >&2
-  echo "  MAKE=<GNU make command name> $0" >&2
-  echo >&2
-  echo "or" >&2
-  echo >&2
-  echo "  MAKE=\"makepp --norc-substitution\" $0" >&2
-  exit 1
+if test -z "`$GNUMAKE -v 2>/dev/null | grep GNU`"; then
+  if test -z "`$GNUMAKE -v 2>/dev/null | grep makepp`"; then
+    echo "GNU make (>= 3.79.1) or makepp (>= 1.19) is required to build FreeType2." >&2
+    echo "Please try" >&2
+    echo "  \`GNUMAKE=<GNU make command name> $0'." >&2
+    echo "or >&2"
+    echo "  \`GNUMAKE=\"makepp --norc-substitution\" $0'." >&2
+    exit 1
+  fi
 fi
 
 # Get `dirname' functionality.  This is taken and adapted from autoconf's
@@ -77,61 +67,34 @@ ft2_dir=`(dirname "$0") 2>/dev/null                         ||
 abs_curr_dir=`pwd`
 abs_ft2_dir=`cd "$ft2_dir" && pwd`
 
-# `--srcdir=' option can override abs_ft2_dir
+# build a dummy Makefile if we are not building in the source tree
 
-if test $# -gt 0; then
-  for x in "$@"; do
-    case x"$x" in
-    x--srcdir=*)
-      abs_ft2_dir=`echo $x | sed 's/^--srcdir=//'` ;;
-    esac
-  done
-fi
-
-# build a dummy Makefile if we are not building in the source tree;
-# we use inodes to avoid issues with symbolic links
-inode_src=`ls -id $abs_ft2_dir | awk '{print $1}'`
-inode_dst=`ls -id $abs_curr_dir | awk '{print $1}'`
-
-if test $inode_src != $inode_dst; then
-  if test ! -d docs; then
-    mkdir docs
-    echo "Copying documentation assets"
-    cp -R $abs_ft2_dir/docs/markdown $abs_curr_dir/docs
-  fi
-  if test ! -r $abs_curr_dir/modules.cfg; then
-    echo "Copying \`modules.cfg'"
-    cp $abs_ft2_dir/modules.cfg $abs_curr_dir
-  fi
+if test "$abs_curr_dir" != "$abs_ft2_dir"; then
+  mkdir reference
+  echo "Copying \`modules.cfg'"
+  cp $abs_ft2_dir/modules.cfg $abs_curr_dir
   echo "Generating \`Makefile'"
-  echo "TOP_DIR        := $abs_ft2_dir"           > Makefile
-  echo "OBJ_DIR        := $abs_curr_dir"         >> Makefile
-  echo "OBJ_BUILD      := \$(OBJ_DIR)"           >> Makefile
-  echo "DOC_DIR        := \$(OBJ_DIR)/docs"      >> Makefile
-  echo "FT_LIBTOOL_DIR := \$(OBJ_DIR)"           >> Makefile
-  echo "ifndef FT2DEMOS"                         >> Makefile
-  echo "  include \$(TOP_DIR)/Makefile"          >> Makefile
-  echo "else"                                    >> Makefile
-  echo "  TOP_DIR_2 := \$(TOP_DIR)/../ft2demos"  >> Makefile
-  echo "  PROJECT   := freetype"                 >> Makefile
-  echo "  CONFIG_MK := \$(OBJ_DIR)/config.mk"    >> Makefile
-  echo "  include \$(TOP_DIR_2)/Makefile"        >> Makefile
-  echo "endif"                                   >> Makefile
+  echo "TOP_DIR   := $abs_ft2_dir"               > Makefile
+  echo "OBJ_DIR   := $abs_curr_dir"             >> Makefile
+  echo "OBJ_BUILD := \$(OBJ_DIR)"               >> Makefile
+  echo "DOC_DIR   := \$(OBJ_DIR)/reference"     >> Makefile
+  echo "LIBTOOL   := \$(OBJ_DIR)/libtool"       >> Makefile
+  echo "ifndef FT2DEMOS"                        >> Makefile
+  echo "  include \$(TOP_DIR)/Makefile"         >> Makefile
+  echo "else"                                   >> Makefile
+  echo "  TOP_DIR_2 := \$(TOP_DIR)/../ft2demos" >> Makefile
+  echo "  PROJECT   := freetype"                >> Makefile
+  echo "  CONFIG_MK := \$(OBJ_DIR)/config.mk"   >> Makefile
+  echo "  include \$(TOP_DIR_2)/Makefile"       >> Makefile
+  echo "endif"                                  >> Makefile
 fi
 
 # call make
 
 CFG=
-# work around zsh bug which doesn't like `${1+"$@"}'
-case $# in
-0) ;;
-*) for x in "$@"; do
-     case x"$x" in
-     x--srcdir=* ) CFG="$CFG '$x'/builds/unix" ;;
-     *) CFG="$CFG '$x'" ;;
-     esac
-   done ;;
-esac
-CFG=$CFG $MAKE setup unix
+for x in ${1+"$@"}; do
+  CFG="$CFG \"$x\""
+done
+CFG=$CFG $GNUMAKE setup unix
 
 # eof
